---
#peer1
server:
  port: 8001
profiles: peer1
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      peer2: http://peer2:8002/eureka/
      peer3: http://peer3:8003/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
instance:
    hostname: peer1
spring:
  application:
    name: weweb-eureka

---
#peer2
server:
  port: 8002
profiles: peer2
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      peer1: http://peer1:8001/eureka/
      peer3: http://peer3:8003/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
instance:
    hostname: peer2
spring:
  application:
    name: weweb-eureka

---
#peer3
server:
  port: 8003
profiles: peer3
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      peer1: http://peer1:8001/eureka/
      peer2: http://peer2:8002/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
instance:
    hostname: peer3
spring:
  application:
    name: weweb-eureka

