spring:
  application:
    name: weweb-hystrix
server:
  port: 9001
eureka:
  client:
   service-url:
      # 实际测试：若修改尾部的eureka为其它的，比如/myeureka，注册中心启动没问题，但服务端在注册时会失败
      # 报告异常：com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
      defaultZone: http://127.0.0.1:8001/eureka
feign:
  hystrix:
    enabled: true
